---
org: encapsulate

default_node_types:
  - validator
  - default

tmp_dir: /tmp

storyprotocol:
  validator:
    execution:
      chain_id: iliad
      syncmode: full
      source_url: https://story-geth-binaries.s3.us-west-1.amazonaws.com/geth-public
      ports:
        auth_rpc_port: 8551
        p2p_port: 30304
      file_extension: tar.gz
    consensus:
      chain_id: iliad
      source_url: https://story-geth-binaries.s3.us-west-1.amazonaws.com/story-public
      ports:
        p2p_port: 26656
        rpc_port: 26657
      file_extension: tar.gz
      moniker_name: "{{ org }}-{{ project }}-{{ env }}"
