---
storyprotocol:
  validator:
    execution:
      version: v0.10.0
      go:
        version: 1.22.8
      chain_id: odyssey
    consensus:
      version: v0.12.1
      go:
        version: 1.22.8
      chain_id: odyssey
