---
execution_jwt_secret_file_name: jwtsecret
execution_service_default_binary_name: geth-{{ ansible_system | lower }}-{{ system_architecture }}
execution_syncmode: full
execution_environment_general_file_name: "{{ service_identifier }}.env"

execution_type_settings:
  http:
    enable: true
    address:
      validator: 127.0.0.1
      fullnode: 0.0.0.0
  metrics:
    enable: true
    address:
      default: 0.0.0.0
