---
---
execution_ufw_rules:
  validator:
    - port: "{{ execution_p2p_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: execution_p2p_port

    - port: "{{ execution_metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: execution_metrics_port

  fullnode:
    - port: "{{ execution_p2p_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: execution_p2p_port

    - port: "{{ execution_http_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: execution_http_port

    - port: "{{ execution_metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: execution_metrics_port
