---
- name: Set up story node consensus client
  hosts: all
  become: true
  gather_facts: false
  vars:
    allowed_node_types: [validator]
    client: consensus
  vars_files:
    - group_vars/all.yml
    - group_vars/{{ env }}.yml
    - group_vars/vault.yml
  tasks:
    - name: Setup environment and run consensus role
      when: type in allowed_node_types
      block:
        - name: Include environment setup tasks
          ansible.builtin.include_tasks: tasks/setup_environment.yml
        - name: Include common handlers
          ansible.builtin.include_role:
            name: common
        - name: Include consensus role
          ansible.builtin.include_role:
            name: consensus
