---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ execution_home_dir }}"
    directories: "{{ execution_directories }}"
    log_file_path: "{{ execution_log_file_path }}"

- name: Include build binary task
  ansible.builtin.include_tasks: build_binary.yml

- name: Save jwtsecret
  ansible.builtin.copy:
    content: "{{ vault.storyprotocol[env].jwtsecret }}"
    dest: "{{ execution_jwtsecret_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"

- name: Copy env file
  ansible.builtin.template:
    src: "{{ env }}/normal_env_var"
    dest: "{{ execution_env_dir }}/{{ service_identifier }}.env"
    owner: root
    group: root
    mode: "0644"

- name: Copy execution client systemd service file
  ansible.builtin.template:
    src: "{{ env }}/storyprotocol-execution.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
