---
# config file names
consensus_config_file_name: config.toml
consensus_story_file_name: story.toml
consensus_priv_validator_key_file_name: priv_validator_key.json
consensus_node_key_file_name: node_key.json
consensus_genesis_file_name: genesis.json
consensus_chain_id:
  mainnet:
  testnet: odyssey
consensus_jwt_secret_file_name: jwtsecret
consensus_default_binary_name: story
consensus_execution_engine_api_endpoint: http://localhost:{{ execution_auth_rpc_port }}
