---
# config file names
consensus_config_file_name: config.toml
consensus_story_file_name: story.toml
consensus_priv_validator_key_file_name: priv_validator_key.json
consensus_consensus_key_file_name: node_key.json
consensus_genesis_file_name: genesis.json

consensus_jwtsecret_file_name: jwtsecret
consensus_default_binary_name: story
