---
execution_home_dir: /opt/{{ service_identifier }}

execution_bin_dir: "{{ execution_home_dir }}/bin"
execution_data_dir: "{{ execution_home_dir }}/data"
execution_jwtsecret_dir: "{{ execution_home_dir }}/jwtsecret"
execution_log_dir: "{{ execution_home_dir }}/log"

execution_directories:
  - "{{ execution_home_dir }}"
  - "{{ execution_bin_dir }}"
  - "{{ execution_data_dir }}"
  - "{{ execution_jwtsecret_dir }}"
  - "{{ execution_log_dir }}"

execution_log_file_path: "{{ execution_log_dir }}/{{ service_identifier }}.log"
execution_jwtsecret_path: "{{ execution_jwtsecret_dir }}/{{ execution_jwtsecret_file_name }}"
