---
consensus_home_dir: /opt/{{ service_identifier }}

consensus_bin_dir: "{{ consensus_home_dir }}/bin"
consensus_log_dir: "{{ consensus_home_dir }}/log"
consensus_jwtsecret_dir: "{{ consensus_home_dir }}/jwtsecret"

consensus_directories:
  - "{{ consensus_home_dir }}"
  - "{{ consensus_bin_dir }}"
  - "{{ consensus_jwtsecret_dir }}"
  - "{{ consensus_log_dir }}"

consensus_log_file_path: "{{ consensus_log_dir }}/{{ service_identifier }}.log"
consensus_jwtsecret_path: "{{ consensus_jwtsecret_dir }}/{{ consensus_jwtsecret_file_name }}"
